apiVersion: v1
kind: Service
metadata:
  name: app_nodejs
  labels:
    {{- include "..labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8085
      targetPort: 8085
      protocol: TCP
      name: http
  selector:
    {{- include "..selectorLabels" . | nindent 4 }}
